### ISSUE TITLE
How to use BertTokenizer?

### ISSUE THREAD

**Issue by jonathan-goodrx** [huggingface/swift-transformers#72]
what is the best way to use the BertTokenizer? its not a public file so I'm not sure whats the best way to use it

**Comment by pcuenca** [comment]
You are right, @jonathan-goodrx. In general, tokenizers are expected to be used using the `AutoTokenizer.from(pretrained:)` method, but `BertTokenizer` does not yet follow that pattern (some of the pieces are hardcoded instead of relying on `BertPreTokenizer` and `BertNormalizer` configuration components).

For now, I've opened https://github.com/huggingface/swift-transformers/pull/73 to make the class public to unlock your use. Once it's merged, you'd use it like this test shows: https://github.com/huggingface/swift-transformers/blob/3bd02269b7797ade67c15679a575cd5c6f203ce6/Tests/TokenizersTests/BertTokenizerTests.swift#L36. You need to supply the vocabulary mapping.

Would that be helpful for your use case?

In parallel, I'll work in an implementation that follows the same pattern as the other tokenizers in the repo, so it can be used with the `AutoTokenizer.from` methods.

**Comment by jonathan-goodrx** [comment]
that works for me, thank you

**Comment by jonathan-goodrx** [comment]
@pcuenca could you bump the library when you get a chance 🙏

**Comment by pcuenca** [comment]
@jonathan-goodrx Done!
